# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server.

# Site Settings
locale                   : "en-US"
title                    : "Ben Kennedy"
title_separator          : "|"
subtitle                 : "PhD Candidate | AI Researcher & Developer"
name                     : "Ben Kennedy"
description              : "PhD Candidate in Artificial Intelligence specializing in cognitive augmentation through SCAN & SCANUE systems. Published researcher and experienced project manager."
url                      : "https://levytate.github.io"
baseurl                  : "/profile"
repository               : "levytate/profile"
teaser                   : # path of fallback teaser image
logo                     : # path of logo image to use in masthead
masthead_title           : "Ben Kennedy"
breadcrumbs              : true
words_per_minute         : 200
search                   : true # Enable site-wide search
search_full_content      : true # Search page content, not just titles
search_provider          : lunr # Use Lunr search engine

# SEO and Social Media
og_image                 : # Open Graph default image
social:
  type                   : Person # Person or Organization (defaults to Person)
  name                   : Ben Kennedy # If the user or organization name differs from the site's name
  links:
    - "https://www.linkedin.com/in/benjaminjoelkennedy"
    - "https://github.com/levytate"

# Site Author
author:
  name             : "Ben Kennedy"
  avatar           : # path of avatar image
  bio              : "PhD Candidate in AI | Developer of SCAN/SCANUE | Empowering Cognition with Advanced AI"
  location         : "Jamestown, North Carolina"
  email            : "benjaminjoelkennedy+linkedin@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:benjaminjoelkennedy+linkedin@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/benjaminjoelkennedy"
    - label: "GitHub (Levy Tate)"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/levytate"
    - label: "University"
      icon: "fas fa-fw fa-university"
      url: "https://www.captechu.edu"
    - label: "Research"
      icon: "fas fa-fw fa-brain"
      url: "/research/"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/benjaminjoelkennedy"
    - label: "GitHub (Development)"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/levytate"
    - label: "Capitol Technology University"
      icon: "fas fa-fw fa-university"
      url: "https://www.captechu.edu"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:benjaminjoelkennedy+linkedin@gmail.com"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Typography and Appearance
typography:
  font_family: "PT Serif" # Professional serif font for academic content
  heading_font_family: "PT Sans" # Clean sans-serif for headings

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"  
minimal_mistakes_skin: "contrast" # Clean, professional with excellent readability

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      show_date: true
      read_time: false
      words_per_minute: 200

# Collections
collections:
  research:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/